export const ACTION_ADD_STEP = 'ACTION_ADD_STEP'
export const ACTION_STAGE_RESTART = 'ACTION_STAGE_RESTART'
export const ACTION_SET_STEP_CURRENT = 'ACTION_SET_STEP_CURRENT'
export const ACTION_SET_STAGE = 'ACTION_SET_STAGE'

export const FIELD_BACKGROUND_EMPTY = 'FIELD_BACKGROUND_EMPTY'
export const FIELD_BACKGROUND_TARGET = 'FIELD_BACKGROUND_TARGET'
export const FIELD_BACKGROUND_WALL = 'FIELD_BACKGROUND_WALL'

export const FIELD_STEP_INIT = 'FIELD_STEP_INIT'
export const FIELD_STEP_UP = 'FIELD_STEP_UP'
export const FIELD_STEP_DOWN = 'FIELD_STEP_DOWN'
export const FIELD_STEP_LEFT = 'FIELD_STEP_LEFT'
export const FIELD_STEP_RIGHT = 'FIELD_STEP_RIGHT'
export const FIELD_STEP_FINISH = 'FIELD_STEP_FINISH'

export const LEVEL_PREVIOUS = 'LEVEL_PREVIOUS'
export const LEVEL_NEXT = 'LEVEL_NEXT'

export const HISTORY_BUTTON_BACK = 'HISTORY_BUTTON_BACK'
export const HISTORY_BUTTON_FORWARD = 'HISTORY_BUTTON_FORWARD'